/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author DavidAnacona
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        this.setLocationRelativeTo(this);
        SetImageLabel(ascensorAbierto1, "src/imagen/ascensorAbierto.png");
        SetImageLabel(ascensorCerrado1, "src/imagen/ascensorCerrado.png");
        SetImageLabel(ascensorAbierto2, "src/imagen/ascensorAbierto.png");
        SetImageLabel(ascensorCerrado2, "src/imagen/ascensorCerrado.png");
        SetImageLabel(ascensorAbierto3, "src/imagen/ascensorAbierto.png");
        SetImageLabel(ascensorCerrado3, "src/imagen/ascensorCerrado.png");
        SetImageLabel(ascensorAbierto4, "src/imagen/ascensorAbierto.png");
        SetImageLabel(ascensorCerrado4, "src/imagen/ascensorCerrado.png");
        SetImageLabel(ascensorAbierto5, "src/imagen/ascensorAbierto.png");
        SetImageLabel(ascensorCerrado5, "src/imagen/ascensorCerrado.png");
        SetImageLabel(ascensorAbierto6, "src/imagen/ascensorAbierto.png");
        SetImageLabel(ascensorCerrado6, "src/imagen/ascensorCerrado.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ascensorAbierto1 = new javax.swing.JLabel();
        ascensorCerrado1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        subirPiso1 = new javax.swing.JButton();
        ascensorAbierto2 = new javax.swing.JLabel();
        ascensorCerrado2 = new javax.swing.JLabel();
        ascensorAbierto3 = new javax.swing.JLabel();
        ascensorCerrado3 = new javax.swing.JLabel();
        ascensorAbierto4 = new javax.swing.JLabel();
        ascensorCerrado4 = new javax.swing.JLabel();
        ascensorAbierto5 = new javax.swing.JLabel();
        ascensorCerrado5 = new javax.swing.JLabel();
        ascensorAbierto6 = new javax.swing.JLabel();
        ascensorCerrado6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        subirPiso2 = new javax.swing.JButton();
        subirPiso3 = new javax.swing.JButton();
        subirPiso4 = new javax.swing.JButton();
        subirPiso5 = new javax.swing.JButton();
        bajarPiso2 = new javax.swing.JButton();
        bajarPiso5 = new javax.swing.JButton();
        bajarPiso4 = new javax.swing.JButton();
        bajarPiso9 = new javax.swing.JButton();
        bajarPiso3 = new javax.swing.JButton();
        piso6 = new javax.swing.JButton();
        piso1 = new javax.swing.JButton();
        piso2 = new javax.swing.JButton();
        piso3 = new javax.swing.JButton();
        piso4 = new javax.swing.JButton();
        piso5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ascensorAbierto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(ascensorAbierto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, 100, 100));

        ascensorCerrado1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(ascensorCerrado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, 100, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel1.setText("Piso 6");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        subirPiso1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/subir.png"))); // NOI18N
        jPanel1.add(subirPiso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 650, 50, 50));

        ascensorAbierto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(ascensorAbierto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 100, 100));

        ascensorCerrado2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(ascensorCerrado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 100, 100));

        ascensorAbierto3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(ascensorAbierto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 100, 100));

        ascensorCerrado3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(ascensorCerrado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 100, 100));

        ascensorAbierto4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(ascensorAbierto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 100, 100));

        ascensorCerrado4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(ascensorCerrado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 100, 100));

        ascensorAbierto5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(ascensorAbierto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 100, 100));

        ascensorCerrado5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(ascensorCerrado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 100, 100));

        ascensorAbierto6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(ascensorAbierto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 100, 100));

        ascensorCerrado6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(ascensorCerrado6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 100, 100));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel2.setText("Piso 1");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel3.setText("Piso 2");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel4.setText("Piso 3");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel5.setText("Piso 4");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jLabel6.setText("Piso 5");
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        subirPiso2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/subir.png"))); // NOI18N
        jPanel1.add(subirPiso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, 50, 50));

        subirPiso3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/subir.png"))); // NOI18N
        jPanel1.add(subirPiso3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 50, 50));

        subirPiso4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/subir.png"))); // NOI18N
        jPanel1.add(subirPiso4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 50, 50));

        subirPiso5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/subir.png"))); // NOI18N
        jPanel1.add(subirPiso5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 50, 50));

        bajarPiso2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/bajar.png"))); // NOI18N
        jPanel1.add(bajarPiso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 50, 50));

        bajarPiso5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/bajar.png"))); // NOI18N
        jPanel1.add(bajarPiso5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 50, 50));

        bajarPiso4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/bajar.png"))); // NOI18N
        jPanel1.add(bajarPiso4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 50, 50));

        bajarPiso9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/bajar.png"))); // NOI18N
        jPanel1.add(bajarPiso9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 50, 50));

        bajarPiso3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/bajar.png"))); // NOI18N
        jPanel1.add(bajarPiso3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 50, 50));

        piso6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/6.png"))); // NOI18N
        jPanel1.add(piso6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 40, 40));

        piso1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/1.png"))); // NOI18N
        jPanel1.add(piso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 40, 40));

        piso2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/2.png"))); // NOI18N
        jPanel1.add(piso2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 40, 40));

        piso3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/3.png"))); // NOI18N
        jPanel1.add(piso3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 40, 40));

        piso4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/4.png"))); // NOI18N
        jPanel1.add(piso4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 40, 40));

        piso5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/5.png"))); // NOI18N
        jPanel1.add(piso5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }
    
    private void SetImageLabel(JLabel labelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
        labelName.setIcon(icon);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ascensorAbierto1;
    private javax.swing.JLabel ascensorAbierto2;
    private javax.swing.JLabel ascensorAbierto3;
    private javax.swing.JLabel ascensorAbierto4;
    private javax.swing.JLabel ascensorAbierto5;
    private javax.swing.JLabel ascensorAbierto6;
    private javax.swing.JLabel ascensorCerrado1;
    private javax.swing.JLabel ascensorCerrado2;
    private javax.swing.JLabel ascensorCerrado3;
    private javax.swing.JLabel ascensorCerrado4;
    private javax.swing.JLabel ascensorCerrado5;
    private javax.swing.JLabel ascensorCerrado6;
    private javax.swing.JButton bajarPiso2;
    private javax.swing.JButton bajarPiso3;
    private javax.swing.JButton bajarPiso4;
    private javax.swing.JButton bajarPiso5;
    private javax.swing.JButton bajarPiso9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton piso1;
    private javax.swing.JButton piso2;
    private javax.swing.JButton piso3;
    private javax.swing.JButton piso4;
    private javax.swing.JButton piso5;
    private javax.swing.JButton piso6;
    private javax.swing.JButton subirPiso1;
    private javax.swing.JButton subirPiso2;
    private javax.swing.JButton subirPiso3;
    private javax.swing.JButton subirPiso4;
    private javax.swing.JButton subirPiso5;
    // End of variables declaration//GEN-END:variables
}
